"""
CitizenAlert — FastAPI Backend
===============================
Research: CitizenAlert: A Geo-Aware, Citizen-Assisted Multi-Purpose
Public Safety Alert System for Sri Lanka
Author : Tanuj Malinda Uduwana | NSBM Green University
Supervisor: Dr. Rasika Ranaweera

Run with:
    uvicorn main:app --reload --port 8000

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

from core.config import settings
from db.database import connect_db, disconnect_db
from api.routes import (
    auth, missing_persons, tvm, cctv,
    disaster_alerts, crime_reports,
    traffic_hazards, public_health, authority,
)

# ── Lifespan: runs on startup & shutdown ─────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    await connect_db()
    print(f"\n{'='*50}")
    print(f"  {settings.APP_NAME} v{settings.APP_VERSION}")
    print(f"  Docs → http://localhost:8000/docs")
    print(f"{'='*50}\n")
    yield
    # Shutdown
    await disconnect_db()


# ── App instance ──────────────────────────────────────────────────────────────
app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    description="""
## CitizenAlert Public Safety Alert System API

A geo-aware, citizen-assisted multi-purpose public safety alert system for Sri Lanka.

### Five Public Safety Domains
- **Missing Persons** — geo-targeted citizen sighting reports with full TVM pipeline
- **Disaster Alerts** — CAP-compliant flood, tsunami, cyclone, earthquake, fire warnings
- **Crime Reports** — hyper-local incident reporting with mandatory Tier-3 authority review
- **Traffic Hazards** — crowdsourced road-segment alerts with consensus auto-verification
- **Public Health** — district-level disease outbreak warnings with medical authority verification

### Core Research Contributions
- **TVM** — 3-tier verification mechanism (novel research contribution)
- **CCTV Boost** — privacy-preserving cross-modal signal corroboration (+15% confidence)
- **Geo-Alert Engine** — PostGIS ST_DWithin location-based targeting (GEOGRAPHY type)
- **UADM** — Unified Alert Data Model normalising all five hazard categories

### Research
Design Science Research (DSR) methodology — Peffers' DSRM
    """,
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS (allows Flutter app + React dashboard to call this API) ──────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # restrict to specific domains in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Routers ───────────────────────────────────────────────────────────────────
app.include_router(auth.router,            prefix="/api/auth",            tags=["Authentication"])
app.include_router(missing_persons.router, prefix="/api/missing-persons", tags=["Missing Persons"])
app.include_router(tvm.router,             prefix="/api/tvm",             tags=["TVM"])
app.include_router(cctv.router,            prefix="/api/cctv",            tags=["CCTV Metadata"])
app.include_router(disaster_alerts.router, prefix="/api/disaster-alerts", tags=["Disaster Alerts"])
app.include_router(crime_reports.router,    prefix="/api/crime-reports",    tags=["Crime Reports"])
app.include_router(traffic_hazards.router, prefix="/api/traffic-hazards", tags=["Traffic Hazards"])
app.include_router(public_health.router,   prefix="/api/public-health",   tags=["Public Health"])
app.include_router(authority.router,       prefix="/api/authority",       tags=["Authority Dashboard"])

# ── Health check ──────────────────────────────────────────────────────────────
@app.get("/api/health", tags=["System"])
async def health():
    return {
        "status": "ok",
        "system": settings.APP_NAME,
        "version": settings.APP_VERSION,
    }